#ifndef PSP_RENDERER_H
#define PSP_RENDERER_H

#include "PR/ultratypes.h"
#include "PR/gbi.h"
#include "sf64thread.h"

#define PSP_RENDERER_DL_MARKER_MAGIC 0x50535200u /* "PSR" plus marker byte. */
#define PSP_RENDERER_DL_MARKER_ID_MASK 0xffu
#define PSP_RENDERER_DL_MARKER_STARFIELD 1u
#define PSP_RENDERER_DL_MARKER_HISTORY_BEGIN 2u
#define PSP_RENDERER_DL_MARKER_HISTORY_END 3u
#define PSP_RENDERER_DL_MARKER_HISTORY_REPLAY 4u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_FULL 5u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_AUTO 6u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_WIDE_UI 7u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_SQUARE_TEXT_UI 8u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_NATIVE_HUD 9u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_TOP_LEFT 10u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_TOP_RIGHT 11u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_BOTTOM_LEFT 12u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_BOTTOM_RIGHT 13u
#define PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_TOP_CENTER 14u
#define PSP_RENDERER_DL_MARKER(tag) \
    (PSP_RENDERER_DL_MARKER_MAGIC | ((u32) (tag) & PSP_RENDERER_DL_MARKER_ID_MASK))
#define PSP_RENDERER_DL_MARKER_MATCH(tag) \
    (((tag) & ~PSP_RENDERER_DL_MARKER_ID_MASK) == PSP_RENDERER_DL_MARKER_MAGIC)
#define PSP_RENDERER_DL_MARKER_ID(tag) \
    ((u32) ((tag) & PSP_RENDERER_DL_MARKER_ID_MASK))
#define PSP_RENDERER_DL_STARFIELD_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_STARFIELD))
#define PSP_RENDERER_DL_HISTORY_BEGIN_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_HISTORY_BEGIN))
#define PSP_RENDERER_DL_HISTORY_END_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_HISTORY_END))
#define PSP_RENDERER_DL_HISTORY_REPLAY_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_HISTORY_REPLAY))
#define PSP_RENDERER_DL_VIEWPORT_FULL_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_FULL))
#define PSP_RENDERER_DL_VIEWPORT_AUTO_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_AUTO))
#define PSP_RENDERER_DL_VIEWPORT_WIDE_UI_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_WIDE_UI))
#define PSP_RENDERER_DL_VIEWPORT_SQUARE_TEXT_UI_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_SQUARE_TEXT_UI))
#define PSP_RENDERER_DL_VIEWPORT_NATIVE_HUD_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_NATIVE_HUD))
#define PSP_RENDERER_DL_VIEWPORT_HUD_TOP_LEFT_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_TOP_LEFT))
#define PSP_RENDERER_DL_VIEWPORT_HUD_TOP_RIGHT_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_TOP_RIGHT))
#define PSP_RENDERER_DL_VIEWPORT_HUD_BOTTOM_LEFT_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_BOTTOM_LEFT))
#define PSP_RENDERER_DL_VIEWPORT_HUD_BOTTOM_RIGHT_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_BOTTOM_RIGHT))
#define PSP_RENDERER_DL_VIEWPORT_HUD_TOP_CENTER_MARKER(pkt) \
    gDPNoOpTag((pkt), PSP_RENDERER_DL_MARKER(PSP_RENDERER_DL_MARKER_VIEWPORT_HUD_TOP_CENTER))
#define PSP_RENDERER_DL_HUD_ANCHOR_PARAM(pkt, x, y) \
    gDPNoOpTag((pkt), (((u32) (u16) (x)) << 16) | (u16) (y))

#define PSP_RENDERER_DL_OP_MTXF G_RESERVED0
#define PSP_RENDERER_DL_OP_INVALIDATE_RGBA16 G_RESERVED1
#define PSP_RENDERER_DL_MTXF(pkt, m, p) \
    gDma1p((pkt), PSP_RENDERER_DL_OP_MTXF, (m), sizeof(Mtx), (p))
#define PSP_RENDERER_DL_INVALIDATE_RGBA16(pkt, texture) \
    gImmp1((pkt), PSP_RENDERER_DL_OP_INVALIDATE_RGBA16, (texture))

void PspRenderer_Init(void);
void PspRenderer_RenderGfxTask(SPTask* task, u32 taskIndex);

void PspRenderer_BeginStarfield(void);
void PspRenderer_AddStar(s16 x, s16 y, u32 n64FillColor);
void PspRenderer_EndStarfield(void);
void PspRenderer_DrawPendingStarfield(void);
int PspRenderer_HistoryHudCacheReady(void);
void PspRenderer_HistoryHudCacheInvalidate(void);

#ifndef PSP_RENDERER_DIAGNOSTICS
#define PSP_RENDERER_DIAGNOSTICS 0
#endif

#if PSP_RENDERER_DIAGNOSTICS
/* Requested/traversed source-star counts for the single aggregate starfield
 * diagnostic line; set once per field by Background_DrawStarfield. */
void PspRenderer_StarfieldDiagCounts(u32 requested, u32 traversed);
#endif

#endif
