#ifndef PSP_RENDER_COMPONENT_H
#define PSP_RENDER_COMPONENT_H

#include "PR/gbi.h"
#include "PR/ultratypes.h"

#ifndef SF64_PSP_PROFILE_COMPONENTS
#define SF64_PSP_PROFILE_COMPONENTS 0
#endif

typedef enum {
    PSP_PROFILE_COMPONENT_UNATTRIBUTED,
    PSP_PROFILE_COMPONENT_MIXED_BATCH,
    PSP_PROFILE_COMPONENT_TITLE_COMMON,
    PSP_PROFILE_COMPONENT_TITLE_FOX,
    PSP_PROFILE_COMPONENT_TITLE_FALCO,
    PSP_PROFILE_COMPONENT_TITLE_SLIPPY,
    PSP_PROFILE_COMPONENT_TITLE_PEPPY,
    PSP_PROFILE_COMPONENT_TITLE_ARWING,
    PSP_PROFILE_COMPONENT_TITLE_STARFOX_LOGO,
    PSP_PROFILE_COMPONENT_TITLE_N64_LOGO,
    PSP_PROFILE_COMPONENT_TITLE_PRESS_START,
    PSP_PROFILE_COMPONENT_TITLE_COPYRIGHT,
    PSP_PROFILE_COMPONENT_TITLE_OTHER_2D,
    PSP_PROFILE_COMPONENT_COUNT
} PspProfileComponent;

#define PSP_PROFILE_DL_COMPONENT_MAGIC 0x50524300u /* "PRC" plus component byte. */
#define PSP_PROFILE_DL_COMPONENT_ID_MASK 0xffu
#define PSP_PROFILE_DL_COMPONENT_TAG(component) \
    (PSP_PROFILE_DL_COMPONENT_MAGIC | ((u32) (component) & PSP_PROFILE_DL_COMPONENT_ID_MASK))
#define PSP_PROFILE_DL_COMPONENT_TAG_MATCH(tag) \
    (((tag) & ~PSP_PROFILE_DL_COMPONENT_ID_MASK) == PSP_PROFILE_DL_COMPONENT_MAGIC)
#define PSP_PROFILE_DL_COMPONENT_TAG_ID(tag) \
    ((u32) ((tag) & PSP_PROFILE_DL_COMPONENT_ID_MASK))

#if SF64_PSP_PROFILE_COMPONENTS
#define PSP_PROFILE_DL_COMPONENT(pkt_expr, component) do { \
        Gfx* pspProfileDlComponentPkt = (pkt_expr); \
        gDPNoOpTag(pspProfileDlComponentPkt, PSP_PROFILE_DL_COMPONENT_TAG(component)); \
    } while (0)
#else
#define PSP_PROFILE_DL_COMPONENT(pkt_expr, component) ((void) 0)
#endif

#endif
